spring:
  application:
    name: order 
  datasource:
    url: jdbc:mysql://localhost:3306/orders 
    username: root 
    password: Pass@123 
  jpa:
    hibernate:
      ddl-auto: create 
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect 

server:
  port: 8085 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 
